### ISSUE TITLE
choreonoid終了時にSegmentation faultが発生する．

### ISSUE THREAD

**Issue by Hiroaki-Masuzawa** [IRSL-tut/irsl_docker#8]
dockerにてirsl_systemのイメージを実行し，choreonoidを起動，終了させるとchoreonoidでSegmentation faultが発生する．
gdbでback traceを取得すると添付のテキストの通り．
[back_trace.txt](https://github.com/IRSL-tut/irsl_docker/files/11268248/back_trace.txt)

[jupyterプラグイン](https://github.com/IRSL-tut/jupyter_plugin)の影響とも考えたが，私には判断つかなかったのでirsl_dockerのissueとする．

**Comment by YoheiKakiuchi** [comment]
だいぶ前からSegfaultするなと思っていたのですが、機能には問題ないと思っていて手をつけていませんでした。

1. 具体的になにか問題が発生しますか?

2. RobotAssembler単体だと発生しないでしょうか?
簡単には choreonoid_ws/install/lib/choreonoid-1.8/libCnoidJupyterPlugin.so を移動させるとJupyterPluginは読まなくなるかと思います。

**Comment by Hiroaki-Masuzawa** [comment]
> 具体的になにか問題が発生しますか?

何も問題は発生しておりません．本Issueは単純に本件が既知であるにしておく必要があると思って作成しました．

>  RobotAssembler単体だと発生しないでしょうか?
>   簡単には choreonoid_ws/install/lib/choreonoid-1.8/libCnoidJupyterPlugin.so を移動させるとJupyterPluginは読まなくなるかと思います。

RobotAssembler単体だと発生しませんでした．
